image: Visual Studio 2017

platform:
    - x64

environment:
  BIT: 64
  COMPILER: msys2
  MSYS2_ARCH: x86_64
  MSYS2_DIR: msys64
  MSYSTEM: MINGW64
  PATH: c:\msys64\usr\bin;c:\msys64\mingw64\bin;C:\msys64\usr\local\bin\;%PATH%
  PLATFORM: x64
  matrix:
    - LISP: sbcl-bin
    - LISP: ccl-bin
    - LISP:

install:
  - bash -lc "curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh"
  - ros install neil-lindquist/ci-utils #for asdf-register-project and run-fiveam
  - ros exec asdf-register-project.ros
#  - ros install prove #for run-prove
#  - ros install rove #for [run-] rove

build: off

test_script:
  - ros exec run-fiveam.ros -e t -l foo/test :foo-tests
  #- ros exec run-prove foo.asd
  #- ros exec rove foo.asd
