# Based on https://pastebin.com/u4gUKtYN and https://github.com/realark/cl-sample-game/blob/master/azure-pipelines.yaml

trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

jobs:
  - job: 'Test'
    strategy:
      matrix:
        win_sbcl:
          target: 'x86_64-windows-10'
          imageName: 'vs2017-win2016'
          LISP: sbcl-bin
        linux_sbcl:
          target: 'x86_64-unknown-linux-gnu'
          imageName: 'ubuntu-16.04'
          LISP: sbcl-bin
        linux_ccl:
          target: 'x86_64-unknown-linux-gnu'
          imageName: 'ubuntu-16.04'
          LISP: ccl-bin
        mac_sbcl:
          target: 'x86_64-apple-darwin'
          imageName: 'macos-10.13'
          LISP: sbcl-bin
    pool:
      vmImage: $(imageName)

    steps:
      - bash: |
          PATH=$HOME/.roswell/bin:$PATH
          ROSWELL_INSTALL_DIR=$HOME/.roswell
          curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
          ros install neil-lindquist/ci-utils
          asdf-register-project
        displayName: Install roswell and tools
      - bash: |
          PATH=$HOME/.roswell/bin:$PATH
          run-fiveam -e t -l foo/test :foo-tests
          run-fiveam -e t -l foo/test :foo-tests-errors
        displayName: Run Tests
