# Based on https://pastebin.com/u4gUKtYN and https://github.com/realark/cl-sample-game/blob/master/azure-pipelines.yaml

trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

variables:
  ROSWELL_ZIP: https://ci.appveyor.com/api/projects/snmsts/roswell-en89n/artifacts/Roswell-x86_64.zip?branch=master&job=Environment%3A%20MSYS2_ARCH%3Dx86_64,%20MSYS2_BITS%3D64,%20MSYSTEM%3DMINGW64,%20METHOD%3Dcross

jobs:
  - job: 'Test'
    strategy:
      matrix:
        win_sbcl:
          target: 'x86_64-windows-10'
          imageName: 'vs2017-win2016'
          LISP: sbcl-bin
        linux_sbcl:
          target: 'x86_64-unknown-linux-gnu'
          imageName: 'ubuntu-16.04'
          LISP: sbcl-bin
        linux_ccl:
          target: 'x86_64-unknown-linux-gnu'
          imageName: 'ubuntu-16.04'
          LISP: ccl-bin
        mac_sbcl:
          target: 'x86_64-apple-darwin'
          imageName: 'macos-10.13'
          LISP: sbcl-bin
    pool:
      vmImage: $(imageName)

    steps:
      - bash: |
          PATH=$HOME/.roswell/bin:$PATH
          ROSWELL_INSTALL_DIR=$HOME/.roswell
          curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
        displayName: Install Roswell
        condition: ne( variables['Agent.OS'], 'Windows_NT' )
      - pwsh: |
          $env:Path += "$($env:HOME)\.roswell\bin"
          Invoke-WebRequest -Uri $($env:ROSWELL_ZIP) -OutFile Roswell.zip
          7z x -o$($env:HOME) Roswell.zip
          Copy-Item -Path $($env:HOME)\roswell\* -Destination $($env:HOME)\.roswell\bin
          ros install $env:LISP
          ros config
        displayName: Install Roswell
        condition: eq( variables['Agent.OS'], 'Windows_NT' )

      - bash: |
          PATH=$HOME/.roswell/bin:$PATH
          ros install neil-lindquist/ci-utils
          asdf-register-project
          run-fiveam -e t -l foo/test :foo-tests-errors
          run-fiveam -e t -l foo/test :foo-tests
        displayName: Run Tests
