variables:
  LISP: sbcl-bin
  LISP: ccl-bin
  LISP: abcl
  LISP: ecl
  LISP: alisp
  LISP: cmucl

before_script:
  - PATH=$HOME/.roswell/bin:$PATH
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
  - ros install neil-lindquist/ci-utils
  - asdf-register-project

test:
  script:
    - run-fiveam -l foo/test :foo-tests
    - run-fiveam -l foo/test :foo-tests-error
