version: 2

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch-curl
    environment:
      LISP: sbcl-bin
    steps:
       - checkout
       - run: PATH=$HOME/.roswell/bin:$PATH
       - run: curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | bash
       - run: ros install neil-lindquist/ci-utils
       - run: echo $PATH
       - run: run-fiveam -e t -l foo/test :foo-tests
       - run: run-fiveam -e t -l foo/test :foo-tests-error
